version: '2.0'
services:
  web:
    build: .
    env_file:
      - ./.env
      - ./.env.docker
    depends_on:
      - db
      - memcached
      - redis
    volumes:
    - static-assets:/musiclist_application/public
    - local-storage:/musiclist_application/storage
  db:
    image: postgres
    env_file:
      - ./.env.docker-db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - 1080:1080
  memcached:
    image: memcached:alpine
  redis:
    image: redis:alpine
  worker:
    build: .
    command: ./bin/worker
    env_file:
      - ./.env
      - ./.env.docker
    depends_on:
      - db
      - memcached
      - redis
  web-nginx:
    build:
      context: ./docker/web/
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
      - 8000:443 # for development
    volumes:
      - ./certs/localhost:/musiclist_application/certs
      - static-assets:/musiclist_application/public
      - local-storage:/musiclist_application/storage
      - web-logs:/musiclist_application/log
volumes:
  static-assets: {}
  local-storage: {}
  web-logs: {}
